## from https://distillery.rbind.io/posts/2021-03-18-use-github-actions-with-r-markdown-and-distill/
name: Render & Deploy Site
# on: [push]
on:
  push:
  schedule:
    - cron: '55 10,15 * * *'
#    - cron: '40 11,12,15 * * 1,2,3,4,5'
# https://crontab.guru/#5_*_*_*_*
jobs:
  render:
    name: Render report
    # runs-on: macos-latest
    # runs-on: windows-latest
    runs-on: windows-2019
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: 'release'
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install rmarkdown
        run: |
          install.packages(c("rmarkdown","knitr","reshape","plyr","zoo",
                  "rvest","lubridate","flextable","magrittr",
                  "RcppRoll","downloadthis","dataRetrieval",
                  "RCurl","png","jsonlite","httr","sp","mapmisc","rgdal",
                  "raster","rgeos","remotes"))
          # pack.url<-"https://cran.r-project.org/src/contrib/Archive/tmap/tmap_3.3-1.tar.gz"
          # install.packages(pack.url,repos=NULL,type="source")
          remotes::install_github("SwampThingPaul/AnalystHelper")
        shell: Rscript {0}
      - name: Download data
        run: |
          source("./report/dowload_noaa_data.R")
      
      - name: Render Site
        run: |
          rmarkdown::render("./report/RegionalConditions.Rmd", output_format = "html_document")
        shell: Rscript {0}
      - name: setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "SwampThingPaul"
          git config user.email "<>"
      
      - name: Commit results
        run: |
          git add -A 
          git commit -m 'update report' || echo "No changes to commit"
          git pull --ff-only
          git push origin || echo "No changes to commit"
