## from https://distillery.rbind.io/posts/2021-03-18-use-github-actions-with-r-markdown-and-distill/
name: Render & Deploy Site
on: [push]
# on:
#  schedule:
#    - cron: '55 11 * * 1,2,3,4,5'

jobs:
  render:
    name: Render report
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: 'release'
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install rmarkdown
        run: |
          install.packages(c("rmarkdown","knitr","reshape","plyr","zoo",
                             "rvest","lubridate","flextable","magrittr",
                             "grid","RcppRoll","downloadthis","dataRetrieval",
                             "RCurl","remotes","png"))
          remotes::install_github("SwampThingPaul/AnalystHelper")
        shell: Rscript {0}
      - name: Render Site
        run: |
          rmarkdown::render("./report/RegionalConditions.Rmd", output_format = "html_document")
        shell: Rscript {0}
      - name: setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      
      - name: Commit results
        run: |
          git commit -m 'new update' || echo "No changes to commit"
          git push origin master || echo "No changes to commit"